# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51c6c40d3ff9a5ef5c594595409d21935818be1d688e43cfc6b17ab3016fde9ea04791d3b333c4655c28715c7761c891926d86aa452619fc0b4dc608c4f73c76

test:
  secret_key_base: 3f715bb377e3d4cf1433eb0202f865262a9d55061b1134e51205ffbb3f795c4457e51f0fb41fc7cc9fcd34bda9a61e18f9c34358390af683a1e5999b158172e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
